language: android

before_install:
  - yes | sdkmanager --licenses
android:
  components:
    - android-30
    - build-tools-29.0.2

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

script:
  - ./gradlew clean assembleDebug testDebug